dist: xenial
language: java
sudo: true
jdk: openjdk17
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache