version: '3.5'

services:
  postgres:
    container_name: postgres_creator
    image: postgres
    environment:
      POSTGRES_USER: creator
      POSTGRES_PASSWORD: creator_passwd
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: