spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url: jdbc:postgresql://localhost:5432/creator_prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    com:
      chronos: INFO